/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    'date_max': string;
    'date_min': string;
    'init_date': string;
    'locale': string;
    'month_table': boolean;
    'onNext': () => Promise<void>;
    'output_format': string;
    'range': string;
    'weekdayshort': string[];
    'year_table': boolean;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    'date_max'?: string;
    'date_min'?: string;
    'init_date'?: string;
    'locale'?: string;
    'month_table'?: boolean;
    'output_format'?: string;
    'range'?: string;
    'weekdayshort'?: string[];
    'year_table'?: boolean;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


